config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users_admin

  root to: 'home#index'

  ActiveSupport::Notifications.instrument 'routes_loaded.application'
end

app/controllers/users_admin_controller.rb
# frozen_string_literal: true

class UsersAdminController < ApplicationAuthorizedController
  before_action :set_collections, only: %i[edit update new]
  before_action :set_user, only: %i[edit update destroy]
  before_action :format_params, only: %i[update create]

  ACCESS_ID = MENU_ACESSO[:usuarios]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result
               .page(params[:page])
               .per(30)
               .without_count

    @users = @users.order(:id) if @q.sorts.empty?
  end

  def edit; end

  def update
    User.transaction do
      @user.user_accesses.destroy_all unless access_params.empty?

      UserAccess.create_to_user(@user, access_params) if access_params.present?
      true
    end

    return redirect_to users_admin_index_path, notice: 'Usuário atualizado com sucesso!' if @user.update(user_params)

    render :edit, collection: set_collections
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if params[:user][:password] != params[:user][:password_confirmation]
      return redirect_to request.referer, alert: 'Senhas não conferem!'
    end

    if @user.save
      UserAccess.create_to_user(@user, access_params) if access_params.present?

      return redirect_to users_admin_index_path, notice: 'Usuário registrado com sucesso!'
    end

    render :new, collection: set_collections
  end

  def destroy
    return redirect_to users_admin_index_path, notice: 'Usuário registrado com sucesso!' if @user.destroy

    render :index
  end

  private

  def set_collections
    @accesses = MenuFilter.accesses(MENU_NAV)
  end

  def set_user
    @user = User.find params[:id]
  end

  def format_params
    params[:user][:admin] = params[:user][:admin] == 'true'
  end

  def user_params
    user_p = params.require(:user).permit(:email, :name, :admin)

    if params[:user][:password].present?
      pass_params = params.require(:user).permit(:password, :password_confirmation)
      user_p = user_p.merge(pass_params)
    end

    user_p
  end

  def access_params
    return [] unless params[:access].present?

    params[:access].map(&:to_i)
  end
end

app/views/users_admin/_access_control.haml
- accesses.each do |session|
  .mt-3
    %h3{title: "session[#{count}]"}= session[:description]
  .row.p-3
    - session[:items].each do |block|
      - block.each do |header, items|
        .col-md-12.mb-3.py-3.border
          .row.mb-3
            %h5= header

          .row
            - items.each do |item|
              .col-md-3.d-flex.mb-2
                .check-switch
                  .check-switcher
                    = check_box_tag "access[]", item[:id], @user.user_menu_items.include?(item[:id]), id: "access_#{count}_id", class: 'switch'
                    %label{class: 'label-switch success', for: "access_#{count}_id"}

                %label{for: "access_#{count}_id"}= item[:description]

              - count += 1

app/views/users_admin/_filter.haml
.dropdown.col-md-2
  %button#dropdownFilter.btn.btn-default.dropdown-toggle{'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-bs-toggle': 'dropdown', type: 'button'}
    = icon('fa-solid', 'sliders-h')
    Filtrar

  .dropdown-menu.p-2{'aria-labelledby': 'dropdownFilter'}
    = search_form_for @q, url: users_admin_index_path do |f|
      .form-group
        = f.label :name_cont, 'Name'
        = f.search_field :name_cont, class: 'form-control'

      .d-grid.gap-2
        = f.submit class: 'btn btn-primary mt-3', value: 'Filtrar'

        - if params[:q].present?
          = link_to request.path, class:'btn btn-default' do
            = icon('fa-solid', 'times')
            Limpar Filtros

app/views/users_admin/_form.haml
= form_for @user, url: users_admin_index_path do |f|
  .row
    .form-group.mb-3.col-md-4
      = f.label :name
      = f.text_field :name, {class: 'form-control'}
    .form-group.mb-3.col-md-4
      = f.label :email
      = f.text_field :email, {class: 'form-control'}

  .row
    .form-group.mb-3.col-md-4
      = f.label :password
      = f.password_field :password, {class: 'form-control'}

    .form-group.mb-3.col-md-4
      = f.label :password_confirmation
      = f.password_field :password_confirmation, {class: 'form-control'}

  .row
    - if current_user.admin?
      .form-group.mb-3.col-md-2
        = f.label :admin
        = f.select :admin, options_for_select([["Sim", "true"], ["Não", "false"]], { selected: @user.admin? ? "true" : "false"}), {prompt: "Selecione..."}, {class: "form-control"}
  .row
    .form-group.mb-3.col-md-2
      %button.btn.btn-success{type: 'submit'}
        = icon('fa-regular', 'floppy-disk')
        Salvar

  .row
    %h2.form-head-title.ml-3 Acesso Avançado
    .col-12
      = render 'access_control', accesses: @accesses, count: 0, permitions: true

app/views/users_admin/edit.haml
= title 'Editar usuário'

.row.justify-content-end.mb-3
  .col-md-2.d-grid
    = link_to users_admin_path(@user), method: :delete, class: 'btn btn-danger', data: {confirm: "Você tem certeza que deseja remover o Usuário?"} do
      = icon('fa-regular', 'trash-can')
      Remover

= form_for @user, url: users_admin_path do |f|
  .row
    .col-md-4.mb-3
      = f.label :name
      = f.text_field :name, {class: 'form-control'}
    .col-md-4.mb-3
      = f.label :email
      = f.text_field :email, {class: 'form-control'}

  .row
    - if current_user.admin?
      .col-md-4.mb-3
        = f.label :password
        = f.password_field :password, {class: 'form-control'}
  
      .col-md-4.mb-3
        = f.label :password_confirmation
        = f.password_field :password_confirmation, {class: 'form-control'}

  .row
    - if current_user.admin?
      .col-md-2.mb-3
        = f.label :admin
        = f.select :admin, options_for_select([["Sim", "true"], ["Não", "false"]], { selected: @user.admin? ? "true" : "false"}), {prompt: "Selecione..."}, {class: "form-control"}
  .row
    .col-md-2.mb-3
      %button.btn.btn-success{type: 'submit'}
        = icon('fa-regular', 'floppy-disk')
        Salvar

  .row
    %h2.form-head-title.ml-3 Acesso Avançado
    .col-12
      = render 'access_control', accesses: @accesses, count: 0, permitions: true

app/views/users_admin/index.haml
= title 'Usuários'

.row.justify-content-between.mb-3
  = render 'filter'
  .col-md-2.d-grid
    = link_to 'Novo', new_users_admin_path, class: 'btn btn-primary'

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Email
      %th.table-actions
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td.text-center
          = link_to edit_users_admin_path(user), title: 'Editar', class: 'btn btn-sm btn-warning mx-1' do
            = icon('fa-solid', 'pen-to-square')

app/views/users_admin/new.haml
= title 'Novo usuário'
= render 'form'